
let findings = [
    {
          ID: "1",
          HOST_NAME: "Zeus",
          IP_PORT: "1.1.1.1",
          FINDING_TYPE: "Input Validation",
          DESCRIPTION: "Blind SQL Injection",
          LONG_DESCRIPTION: "Blind SQL Injection",
          STATUS: "OPEN",
          POSTURE: "NEARSIDER",
          C: "n",
          I: "n",
          A: "n",
          IMP_SCORE: "0",
          CAT: "|",
          CAT_SCORE: "10",
          CM: "10",
          Vs_n: "0",
          Vs_q: "0",
          RELEVANCE_OF_THREAT: "Confirmed",
          LIKELIHOOD: "Info",
          IMPACT: "VL",
          IMPACT_RATIONALE_HIDE: "Degrades capability X1",
          RISK: "Info",
          MITIGATION_1_LINER: "Your script should filter metacharacters from user input.",
          MITIGATION_HIDE: "Your script should filter metacharacters from user input.Check detailed information for more information about fixing this vulnerability.",
          ANALYST: "FJ",
    },
    {
      ID: "2",
      HOST_NAME: "insecure.snorby.org",
      IP_PORT: "1.1.1.1",
      FINDING_TYPE: "information disclosure",
      DESCRIPTION: "Apache HTTPD: error responses can expose cookies (CVE-2012-0053)",
      LONG_DESCRIPTION: "N/A",
      STATUS: "OPEN",
      POSTURE: "Insider-1",
      C: "y",
      I: "y",
      A: "y",
      IMP_SCORE: "7",
      CAT: "|",
      CAT_SCORE: "10",
      CM: "7",
      Vs_n: "49",
      Vs_q: "M",
      RELEVANCE_OF_THREAT: "Confirmed",
      LIKELIHOOD: "M",
      IMPACT: "VH",
      IMPACT_RATIONALE_HIDE: "DEGRADES CAPABILITY X 1",
      RISK: "H",
      MITIGATION_1_LINER: "Apache HTTPD >= 2.0 and < 2.0.65",
      MITIGATION_HIDE: "Many platforms and distributions provide pre-built binary packages for Apache HTTP server.  These pre-built packages are usually customized and optimized for a particular distribution, therefore we recommend that you use the packages if they are available for your operating system.",
      ANALYST: "FJ",
},
    {
      ID: "3",
      HOST_NAME: "lucas",
      IP_PORT: "1.1.1.1",
      FINDING_TYPE: "Input Validation",
      DESCRIPTION: "Apache 1.3 HTTP Server Expect Header Cross-Site Scripting",
      LONG_DESCRIPTION: "N/A",
      STATUS: "OPEN",
      POSTURE: "Insider-1",
      C: "y",
      I: "y",
      A: "y",
      IMP_SCORE: "0",
      CAT: "|",
      CAT_SCORE: "10",
      CM: "10",
      Vs_n: "0",
      Vs_q: "0",
      RELEVANCE_OF_THREAT: "Confirmed",
      LIKELIHOOD: "Info",
      IMPACT: "VL",
      IMPACT_RATIONALE_HIDE: "Degrades capability X1",
      RISK: "Info",
      MITIGATION_1_LINER: "Upgrade to the latest version of Apache",
      MITIGATION_HIDE: "Upgrade to the latest version of Apache, which is available for download from the Apache Web site:http://www.apache.org/.",
      ANALYST: "FJ",
    },
    {
      ID: "4",
      HOST_NAME: "snorby.org",
      IP_PORT: "1.1.1.1",
      FINDING_TYPE: "Missing Patch",
      DESCRIPTION: "SSL / TLS Renegotiation Handshakes MiTM Plaintext Data Injection",
      LONG_DESCRIPTION: "N/A",
      STATUS: "OPEN",
      POSTURE : "Insider-1",
      C: "y",
      I: "y",
      A: "y",
      IMP_SCORE: "0",
      CAT: "|",
      CAT_SCORE: "10",
      CM: "10",
      Vs_n: "0",
      Vs_q: "0",
      RELEVANCE_OF_THREAT: "Confirmed",
      LIKELIHOOD: "Info",
      IMPACT: "VL",
      IMPACT_RATIONALE_HIDE: "Degrades capability X1",
      RISK: "Info",
      MITIGATION_1_LINER: "Contact the vendor for specific patch information.",
      MITIGATION_HIDE: "Contact the vendor for specific patch information.",
      ANALYST: "FJ",
    }
    
  ];
  
  export default {
    getFindings() {  
      
      return findings;
    }
  };
  